### ISSUE TITLE
Assignment 5: Backend

### ISSUE THREAD

**Issue by SnejUgal** [InnoSWP/b21-02-anonymous-feedback#79]
- [x] **Select testing frameworks, linters, etc. and justify why we selected them**
 
 - [ ] **Write unit tests**
 
Extra points will be awarded for additional, justified tools 🤡 and for 100% test coverage 🤡🤡

**Comment by fedor-ivn** [comment]
**Testing**: [pytest](https://docs.pytest.org/en/7.1.x/), because it is *de facto* the standard for testing in the python world. The framework has rich ecosystem of libraries, plugins and integrations with other frameworks. Besides, it has well-written documentation, tutorials and big community. [Github actions.](https://github.com/marketplace/actions/run-black-formatter)


**Linter**: flake8, because it glues together pycodestyle, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code. This linter is powerful for catching errors and also fast.

**Formatter**: [black](https://github.com/psf/black), because it is uncompromising Python code formatter. Black saves time from thinking about proper ways of writing things, thanks to strict [black code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html). More than that, black is trusted by famous open source projects and organizations: pytest, Django, Meta, Mozilla.

**Comment by fedor-ivn** [comment]
@SnejUgal @eivankin your opinions are welcome
